### PR TITLE
add translation tags

### PR DESCRIPTION
**Pull request by clubdego974**
Time passes quickly... So, I propose not to wait any longer to push all my proposals for adding tags. I checked them (several times) a few weeks ago, and hope they are correct. But as I'm not a professional developer and this is the first time I've done this, thank you to the developers for checking carefully. I realize that it's a lot of files / changes: that's why I cut into several sub-PR.

### CODE REVIEW

**Comment by climu** [comment]
Impressive work. Sorry for the delay. I ll refresh poeditor now.

**Comment by clubdego974** [comment]
Great. Let me know when you have refreshed Poeditor, so I can add the new translations (only in French)

**Comment by climu** [comment]
Terms have been added on poeditor.

For the record there was one issue:
```
SyntaxError: Translation blocks must not include other block tags: url "account_login" (file openstudyroom/templates/account/password_reset_from_key_done.html, line 15)```
```
I fixed it here (baa721f).

image

**Comment by climu** [comment]
We have a bunch of `<ExtendsNode: extends "full_width.html"> must be the first tag in the template.` here and there I didn't noticed :(

**Pull request merged**
